version: '3.9'
services:
  api:
    build:
      context: ./api # Diretório onde está o Dockerfile da API
    ports:
      - "3000:3000" # Mapeia a porta do container para o host
    volumes:
      - ./api:/app # Atualiza o container ao modificar o código
      - /app/node_modules # Evita sobrescrever os módulos
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend # Diretório onde está o Dockerfile do Frontend
    ports:
      - "4200:80" # Mapeia a porta 80 (Nginx) para a 4200 no host
    volumes:
      - ./frontend:/app # Atualiza o container ao modificar o código
      - /app/node_modules # Evita sobrescrever os módulos
